language: ruby

before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin

script:
- bundle exec jekyll build

cache:
  directories:
  - _vendor/bundle

notifications:
  email: false

env:
  global:
  - secure: SaIT5iAZFgfJOLNXjFSCPqIJJMxLi0sskWKrbnTNYIukfqJfMdoDb8/oJ+BEs/nBKxGPRFtAHN43pQ97HSMdBqv86vxjAIQd85YAAyKIGQMBxDygRhWIaf2qFUOHUNDGL4/HPrhqKaDmvj1C+Rlnd6ovOh6jP/4AWgXT9uy0JHOr+R2giYq92eNl4ELHHOgD3+pZgfNNy4F5BasH9juh/rbnRgRGs0Nz2WrrJ4DGx7AxufM36QVgWIi2TvA5UFvH1Z4FYeeIx2WdtvN0YPMA+WYIpRD5zY9luQOK/d8FjtPmOkgAU1RbHCRT2VRMqULJygJvkq29IUgFKgVVGYtrtOezN00NiFcuhekz6rNeyZIGKDNkEBbbvFBD2X++VewEoVgRpaA4dTLhPJCzVbiTI7BpjaQingL7I2Z/oghtAtBQcdDxXuAlJahvkMzb9xOMDOfG5SWgZPTjwroOdF6v/TP+FEmsLe7rejVMfo1358h0sRiqyt9QG5NHWSPIRdU0KVFaFOFYpdue9gfdjRn2xGzHvSwR6M2ZzO4bNsOKbYsjP4/2EQJQAu8WaiftdAnnF8X31MwyvH+fSfrIEezdoMZO+tHtYSocoUCNjgHvWkiEO/ZjL6UNv2iQKQg6qNFUHrYqEuS+FSlt1aahkWow4T+UtDGe/+602SE4QroJs0Y=
  - secure: etewUiZUUgZOfG+NJISlS7Sl6QajpdYgCK5x2VbDwoOLwyp/dNpZ/NhmlqDw7OFDvFfWXWKoJEKrmUabKm+6eZutlufcCZoiO0OMIppI7Z1XidQbFyIWqjKfpH58IkA4KZVjBvxWbLJfTLsue/ePzI2FWY1s6XfNizYpS4c7mTjJ1GmEGa/4ia6fWGnQbR+wQVRjOWa7PPp/6UdJBJcA51zFbwo7MwU8eO9Usm3xRByuObUiQuKNr8RmFW+g6u1DlX6dCNF4vGprFtjn2A5W3pg2tD/pglRfbtR1kHCKzTXOO/4ro6N2MGUwiGnaHTA9VzdyNAEpJaAyC7PDIeoH94dbB81D8cNgJwkoTLL9ydgucHRCeFAE+/aDr8HXzZrs89OrU89fHagjcXrouKarMzsJsQPaJo2xHIiY3vSAflLfgiNWfWMGpZWZOo6KAQRyfxH5mWyuYJaYDSK0f5F39WzvxGYNQb2+gNzTSpHI3bN+bfZTVKsKFj7BVqqBhOGovYU6CoKQ8KKoLY1gRdsl5LCYJvPTLwfLEc5ZZxUoqVhl34sVacjlGj6lBRoKkVBmdWhwxCDtwDN/8db5vrJoIKC9FjIKNMtb6jBZnFe/W5RsPPq0XQYT8iS0Brhv2bOpj7t7wnnVbXIoZygJKvG2hj2FW2CMQ+55M5lbzvfeu6g=

deploy:
- provider: script
  script: aws s3 sync --acl public-read --delete --region us-gov-west-1 _site s3://status.vets.gov/
  skip_cleanup: true
  on:
    repo: department-of-veterans-affairs/vets.gov-status
    branch: master
