# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vets.gov Status Dashboard
email: vetsdotgov@va.gov
description: > # this means to ignore newlines until "baseurl:"
  A dashboard for Vets.gov projects, and the status of development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vets.gov/status-report" # the base hostname & protocol for your site
github_username:  department-of-veterans-affairs

# Build settings
markdown: kramdown