collections:
  boards:
    output: true

defaults:
  - scope:
      path: ""
      type: boards
    values:
      layout: board

exclude:
  - scripts
  - LICENSE.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - Jenkinsfile

baseurl: "/scorecard"
